[package]
name = "rs-fullstack"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rs-fullstack"

[dependencies]
actix-web = "4.5.1"
rstest = "0.18.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.11"
